[package]
name = "no_debug"
repository = "https://github.com/Cypher1/no_debug"
version = "1.0.2"
edition = "2021"
license = "MIT"
description = "Helper types to omit debug and display info for select values."

[dependencies]
